package com.example.demo.mapper;

import com.example.demo.domain.RedPacketInfo;

public interface RedPacketInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    int insert(RedPacketInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    int insertSelective(RedPacketInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    RedPacketInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    int updateByPrimaryKeySelective(RedPacketInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_info
     *
     * @mbggenerated Fri May 10 14:47:25 CST 2019
     */
    int updateByPrimaryKey(RedPacketInfo record);
}