package com.example.demo.mapper;

import com.example.demo.domain.RedPacketRecord;

public interface RedPacketRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    int insert(RedPacketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    int insertSelective(RedPacketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    RedPacketRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    int updateByPrimaryKeySelective(RedPacketRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table red_packet_record
     *
     * @mbggenerated Fri May 10 14:55:08 CST 2019
     */
    int updateByPrimaryKey(RedPacketRecord record);
}