package com.example.demo.mapper;

import com.example.demo.domain.UserScore;

public interface UserScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    int insert(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    int insertSelective(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    UserScore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    int updateByPrimaryKeySelective(UserScore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_score
     *
     * @mbggenerated Tue Apr 30 10:16:46 CST 2019
     */
    int updateByPrimaryKey(UserScore record);
}